import { Chat } from "../types/chat";

export const sampleChats: Chat[] = [
  {
    id: "1",
    name: "Alice",
    avatar: "https://cdn-icons-png.flaticon.com/512/6596/6596121.png",
    lastMessage: "Hey! How are you?",
    time: "10:30 AM",
    unread: 2,
  },
  {
    id: "2",
    name: "Bob",
    avatar: "https://cdn-icons-png.flaticon.com/512/6596/6596121.png",
    lastMessage: "See you tomorrow!",
    time: "09:15 AM",
  },
  {
    id: "3",
    name: "Charlie",
    avatar: "https://cdn-icons-png.flaticon.com/512/6596/6596121.png",
    lastMessage: "Typing...",
    time: "Yesterday",
    unread: 1,
  },
  {
    id: "1",
    name: "Alice",
    avatar: "https://cdn-icons-png.flaticon.com/512/6596/6596121.png",
    lastMessage: "Hey! How are you?",
    time: "10:30 AM",
    unread: 2,
  },
  {
    id: "2",
    name: "Bob",
    avatar: "https://cdn-icons-png.flaticon.com/512/6596/6596121.png",
    lastMessage: "See you tomorrow!",
    time: "09:15 AM",
  },
  {
    id: "3",
    name: "Charlie",
    avatar: "https://cdn-icons-png.flaticon.com/512/6596/6596121.png",
    lastMessage: "Typing...",
    time: "Yesterday",
    unread: 1,
  },
  {
    id: "1",
    name: "Alice",
    avatar: "https://cdn-icons-png.flaticon.com/512/6596/6596121.png",
    lastMessage: "Hey! How are you?",
    time: "10:30 AM",
    unread: 2,
  },
  {
    id: "2",
    name: "Bob",
    avatar: "https://cdn-icons-png.flaticon.com/512/6596/6596121.png",
    lastMessage: "See you tomorrow!",
    time: "09:15 AM",
  },
  {
    id: "3",
    name: "Charlie",
    avatar: "https://cdn-icons-png.flaticon.com/512/6596/6596121.png",
    lastMessage: "Typing...",
    time: "Yesterday",
    unread: 1,
  },
  {
    id: "1",
    name: "Alice",
    avatar: "https://cdn-icons-png.flaticon.com/512/6596/6596121.png",
    lastMessage: "Hey! How are you?",
    time: "10:30 AM",
    unread: 2,
  },
  {
    id: "2",
    name: "Bob",
    avatar: "https://cdn-icons-png.flaticon.com/512/6596/6596121.png",
    lastMessage: "See you tomorrow!",
    time: "09:15 AM",
  },
  {
    id: "3",
    name: "Charlie",
    avatar: "https://cdn-icons-png.flaticon.com/512/6596/6596121.png",
    lastMessage: "Typing...",
    time: "Yesterday",
    unread: 1,
  },
];
